### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by Eheran1** [rodan/ds3234#3]
This is the output im getting off the example with 2 changes (cs set to 7 and "pinMode(10, OUTPUT);" since pin 10 has to be output for SPI for some reason...):

GET time
1917.05.20 68:24:45
1917.05.20 68:24:50
1917.05.20 68:24:55
1917.05.20 68:25:00
1917.05.20 68:25:05
1917.05.20 68:25:10
1917.05.20 68:25:15
1917.05.20 68:25:20
1917.05.20 68:25:25
1917.05.20 68:25:30
1917.05.20 68:25:35
1917.05.20 68:25:40
1917.05.20 68:25:45

Month, day and seconds seem to be right. First 2 digits of Year and first digit hour obviously not, minutes are 10 too low, so first digit.
Correct output would be eg:
2017.05.20 18:35:45   (where this is GMT and i would currently have GMT +2h here, but thats no issue since the problem exists with summer time saving anyway...

Edit:
If the time is set outside of this library I can correctly read it back with the this library - only with 1917 instead of 2017 as the year:
1917.05.20 21:39:31
1917.05.20 21:39:36
1917.05.20 21:39:41
1917.05.20 21:39:54

**Comment by rodan** [comment]
let's see.
you use 3 different libraries with your hardware and seeing that you cannot get out a valid output you start opening bug requests against the all 3 libs, because the problem is clearly there.
are you for real?

**Comment by rodan** [comment]
step 0. don't open bug reports until you are 100% certain the problem lies outside of your control
step 1. remove battery
step 2. set time/date WITH MY LIBRARY
step 3. read time/date WITH MY LIBRARY

Why? because most libs out there completely and blissfully ignore the century bit

**Comment by Eheran1** [comment]
It was confusing to find issues with several librarys and my fault was at your step 3: I didnt set a newline and/or CR...
Sorry for my nonsense, ur library is indeed working.
