### ISSUE TITLE
A (minor) bug to fix

### ISSUE THREAD

**Issue by WheresWally** [rodan/ds3234#4]
Hi, thanks for the great library.
I notice that nearly all routines for reading and writing the time follow the same process that "could" lead to invalid time/date reading. From the PDF it says the register value is copied upon CS to prevent rollover screwing with the time/date.
My suggestion is to Set CS, read/write all required registers then unset CS.
I know that it would probably be rare to be reading the time/date regs during a rollover.
But to be the best maybe a few adjustment to the code????

From the PDF ...
_When reading or writing the time and date registers,
secondary (user) buffers are used to prevent errors
when the internal registers update. When reading the
time and date registers, the user buffers are synchronized
to the internal registers on the falling edge of CS
or and when the register pointer rolls over to zero. The
time information is read from these secondary registers,
while the clock continues to run. This eliminates the
need to reread the registers in case the main registers
update during a read._

**Comment by rodan** [comment]
Hi,

one of us must be missing something. look for those 

digitalWrite(pin, LOW);
// perform SPI IO
digitalWrite(pin, HIGH);

in all of the lib functions. https://github.com/rodan/ds3234/blob/master/ds3234.cpp
