### ISSUE TITLE
ESP8266 compatibility - only reads the seconds

### ISSUE THREAD

**Issue by WheresWally** [rodan/ds3234#5]
Have you tried it on a ESP8266?
I have it working using a bit-banged version not the inbuilt SPI library.
The seconds seem to read ok, but the subsequent reads dont get the right data.
I did have some luck by setting CS, read all 7 regs then unset CS.
Any thoughts?

```
1900.00.00 00:48:08
1900.00.00 00:52:13
1900.00.00 00:48:18
1900.00.00 00:52:23
1900.00.00 00:48:28
1900.00.00 00:52:33
1900.00.00 00:48:38
1900.00.00 00:52:43
1900.00.00 00:48:48
1900.00.00 00:52:53
1900.00.00 00:48:58
1900.00.00 12:53:03
```

**Comment by rodan** [comment]
no, I did not try it with ESP8266.
as I said in your previous bug I no longer have any of the AVR development kit. so unfortunately this lib is provided just for historical reference.
